on:
    push:
        branches:
            - '**'
    pull_request:
        types: [opened, reopened]

jobs:
    jammy_test:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v3
            - run: make guix_install_noninteractive
            - run: make lint_all
            - run: make chan_install_all
