on: [push, pull_request]


jobs:
    jammy_test:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v3
            - run: make guix_install
            - run: make lint_all
            - run: make install_all
